# Collect Results

In this notebook, I show my improved aggregation relying on more consistent datastructures.

## Imports

In [1]:
# Imports
import os
import numpy as np
import pandas as pd
import json
import sys
import pickle as pkl
import warnings

from os.path import dirname

In [9]:
# Custom

root_dir = dirname(dirname(os.getcwd()))
src_dir = os.path.join(root_dir, 'src')
sys.path.append(src_dir)

import exp
from exp.utils.extra import mem_usage
from exp.runner.RunExp import RunExp
from exp.runner.RunMercs import RunMercs

## Methods

It works like this.

In [3]:
def load_or_make_runner(idx=None, kind='RunExp', root_dir=None, **kwargs):
    
    if kind in {'RunExp'}:
        helper = RunExp()
    elif kind in {'RunMercs'}:
        helper = RunMercs()
    else:
        msg = """
        Did not recognize kind:    {}
        """.format(kind)
        raise ValueError(msg)

    helper.make_config(idx=idx, root_dir=root_dir, **kwargs)
    runner_fname = helper.get_fname(kind)

    if os.path.isfile(runner_fname):
        with open(runner_fname, 'rb') as f:
            runner = pkl.load(f)
        del helper
    else:
        msg = """
        Could not load the actual runner. Using the self-made helper.
        """
        warnings.warn(msg)
        runner = helper
    return runner

## Demo

In [4]:
runner = load_or_make_runner(idx=1, kind='RunExp', root_dir=root_dir)

This is how we aggregate the outputs of this experiment.

In [5]:
runner.aggregate_outputs(save=True)

Now, the runner object has them as attributes

In [6]:
df = runner.qry_codes
df.head()

                 targ  perc_miss
idx f_idx q_idx
10  0     0      (0,)        0.0
          1      (1,)        0.0
          2      (2,)        0.0
          3      (3,)        0.0
          4      (4,)        0.0

But also, since we told it to save, they are also made persistent on disk (currently pickled.)

In [7]:
runner.load_output(kind='qry_codes')

                  targ  perc_miss
idx f_idx q_idx
10  0     0       (0,)        0.0
          1       (1,)        0.0
          2       (2,)        0.0
          3       (3,)        0.0
          4       (4,)        0.0
          5       (5,)        0.0
          6       (6,)        0.0
          7       (7,)        0.0
          8       (8,)        0.0
          9       (9,)        0.0
          10     (10,)        0.0
          11     (11,)        0.0
          12     (12,)        0.0
          13     (13,)        0.0
          14     (14,)        0.0
          15     (15,)        0.0
    1     0       (0,)        0.0
          1       (1,)        0.0
          2       (2,)        0.0
          3       (3,)        0.0
          4       (4,)        0.0
          5       (5,)        0.0
          6       (6,)        0.0
          7       (7,)        0.0
          8       (8,)        0.0
          9       (9,)        0.0
          10     (10,)        0.0
          11     (11,)        0.0
          12     (12,)        0.0
          13     (13,)        0.0
...                ...        ...
11  4     20     (20,)        0.0
          21     (21,)        0.0
          22     (22,)        0.0
          23     (23,)        0.0
          24     (24,)        0.0
          25     (25,)        0.0
          26     (26,)        0.0
          27     (27,)        0.0
          28     (28,)        0.0
          29     (29,)        0.0
          30     (30,)        0.0
          31     (31,)        0.0
          32     (32,)        0.0
          33     (33,)        0.0
          34     (34,)        0.0
          35     (35,)        0.0
          36     (36,)        0.0
          37     (37,)        0.0
          38     (38,)        0.0
          39     (39,)        0.0
          40     (40,)        0.0
          41     (41,)        0.0
          42     (42,)        0.0
          43     (43,)        0.0
          44     (44,)        0.0
          45     (45,)        0.0
          46     (46,)        0.0
          47     (47,)        0.0
          48     (48,)        0.0
          49     (49,)        0.0

[330 rows x 2 columns]

In [8]:
helper=RunExp
helper.make_config(idx=1, root_dir=root_dir)

TypeError: make_config() missing 1 required positional argument: 'self'